# Generated by Django 5.0.7 on 2024-08-06 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('PARTIAL', 'Partial')], default='PENDING')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('ended_on', models.DateTimeField(null=True)),
                ('extra', models.TextField(blank=True)),
                ('progress', models.FloatField(default=0)),
                ('type', models.CharField(choices=[('UPLOAD_DATAFILE', 'Upload a datafile'), ('DOWNLOAD_ARCGIS_LAYER', 'Download an ArcGis Layer')], max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('db_entity_id', models.IntegerField(null=True)),
                ('config_entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.configentity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upload_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UploadDatasetTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('PARTIAL', 'Partial')], default='PENDING')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('ended_on', models.DateTimeField(null=True)),
                ('extra', models.TextField(blank=True)),
                ('progress', models.FloatField(default=0)),
                ('dataset_id', models.IntegerField()),
                ('file_path', models.TextField(blank=True, null=True)),
                ('filename', models.CharField(max_length=200)),
                ('_metadata', models.TextField(blank=True, db_column='metadata', null=True)),
                ('upload_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload_manager.uploadtask')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
