from pydantic import BaseModel, Field


class ImportCrop(BaseModel):
    id: int = Field(default=0)
    name: str = Field(default="")

    crop_yield: float = Field(default=0.0)
    unit_price: float = Field(default=0.0)
    cost: float = Field(default=0.0)
    water_consumption: float = Field(default=0.0)
    labor_input: float = Field(default=0.0)
    truck_trips: float = Field(default=0.0)

    seed_cost: float = Field(default=0.0)
    chemical_cost: float = Field(default=0.0)
    fertilizer_cost: float = Field(default=0.0)
    custom_cost: float = Field(default=0.0)
    contract_cost: float = Field(default=0.0)
    irrigation_cost: float = Field(default=0.0)
    labor_cost: float = Field(default=0.0)
    equipment_cost: float = Field(default=0.0)
    fuel_cost: float = Field(default=0.0)
    other_cost: float = Field(default=0.0)
    feed_cost: float = Field(default=0.0)
    pasture_cost: float = Field(default=0.0)
    land_rent_cost: float = Field(default=0.0)
    other_cash_costs: float = Field(default=0.0)
    total_cash_costs: float = Field(default=0.0)
    establishment_cost: float = Field(default=0.0)
    land_cost: float = Field(default=0.0)
    other_noncash_costs: float = Field(default=0.0)
    total_noncash_costs: float = Field(default=0.0)


class ImportCropType(BaseModel):
    id: int = Field(default=0)
    name: str = Field(default="")
    alfalfa: float = Field(default=0.0)
    almonds: float = Field(default=0.0)
    apples: float = Field(default=0.0)
    apricots: float = Field(default=0.0)
    asparagus: float = Field(default=0.0)
    beans: float = Field(default=0.0)
    blueberries: float = Field(default=0.0)
    corn: float = Field(default=0.0)
    grapes: float = Field(default=0.0)
    mandarins: float = Field(default=0.0)
    nursery: float = Field(default=0.0)
    olives: float = Field(default=0.0)
    other_citrus: float = Field(default=0.0)
    other_fruits_and_nuts: float = Field(default=0.0)
    other_stone_fruits: float = Field(default=0.0)
    pasture: float = Field(default=0.0)
    peaches: float = Field(default=0.0)
    pears: float = Field(default=0.0)
    prunes: float = Field(default=0.0)
    rice: float = Field(default=0.0)
    safflower: float = Field(default=0.0)
    strawberry: float = Field(default=0.0)
    sunflower: float = Field(default=0.0)
    timber: float = Field(default=0.0)
    tomatoes: float = Field(default=0.0)
    vegetables: float = Field(default=0.0)
    walnuts: float = Field(default=0.0)
    wheat: float = Field(default=0.0)
